### ISSUE TITLE
Compatibility issue with Rails 4.2.0.beta1

### ISSUE THREAD

**Issue by k13n** [alexspeller/non-stupid-digest-assets#22]
I just tried this gem to include AmCharts but couldn't manage to get it running. Once I downgraded from rails version 4.2.0.beta1 to 4.1.5 everything worked just fine. Apart from downgrading rails I didn't have to change anything. Is there any known compatibility issue with the latest rails version?

**Comment by janraasch** [comment]
Seems to work fine on `4.2.3`.

**Comment by tylercollier** [comment]
I can confirm it works on 4.2.3.

**Comment by janraasch** [comment]
I suppose this issue can be closed then. (cc: @alexspeller)

**Comment by k13n** [comment]
I haven't been working much with RoR recently and didn't have the time to test the latest RoR version. But thanks to all others for testing and reporting!

**Comment by hut8** [comment]
Right now the README says:

> Currently this gem does not work with rails 4.2 beta. Pull requests welcome!

I'm using the gem with Rails 4.2.5 and it seems to work fine. This issue seems related to the doc. I know this issue is closed, but I just wanted to confirm that this can be removed from the docs (I'll open a PR).

**Comment by alexspeller** [comment]
@hut8 that'd be most appreciated!

**Comment by hut8** [comment]
I will be able to handle this tonight probably.
